Repository swapnilsparsh/Rescue, pull requests merged in 2021-03, with the labels that each got.

#138 Edited the footer of the home page as it had grammatical errors. Fix…
  main_app/templates/main_app/common.html
  main_app/templates/main_app/home.html
Labels: Level0, gssoc21, ready-to-merge

#141 added some commands
  Contributing.md
Labels: Level0, gssoc21, ready-to-merge

#135 Added top button in women_rights.html, helpline_numbers.html and women_laws.html
  main_app/static/Images/top.png
  main_app/static/Images/toph.png
  main_app/templates/main_app/404.html
  main_app/templates/main_app/create_contact.html
  main_app/templates/main_app/delete_contact.html
  main_app/templates/main_app/developers.html
  main_app/templates/main_app/emergency.html
  main_app/templates/main_app/emergency_contact.html
  main_app/templates/main_app/helpline_numbers.html
  main_app/templates/main_app/home.html
  main_app/templates/main_app/login.html
  main_app/templates/main_app/register.html
  main_app/templates/main_app/women_laws.html
  main_app/templates/main_app/women_rights.html
Labels: Level2, gssoc21, ready-to-merge

#152 Register Page Fixed
  main_app/static/Images/signup-image.svg
  main_app/templates/main_app/register.html
Labels: Level2, gssoc21, ready-to-merge

#126 Changes In Navbar as per issue #119
  main_app/templates/main_app/common.html
  main_app/templates/main_app/helpline_numbers.html
  main_app/templates/main_app/home.html
  main_app/templates/main_app/women_laws.html
  main_app/templates/main_app/women_rights.html
Labels: Level2, gssoc21, ready-to-merge

#155 corrected the spelling
  Documentation/women_safety_laws.md
Labels: Level0, gssoc21, ready-to-merge

#156 Added content by adding objective in home page as per issue #146
  main_app/templates/main_app/home.html
Labels: Level1, gssoc21, ready-to-merge

#162 Added option to call by clicking on phone icon in helpline_numbers.html
  main_app/templates/main_app/helpline_numbers.html
Labels: Level2, gssoc21, under review

#177 Improved UI of Register and Sign in templates using Grid
  main_app/templates/main_app/login.html
  main_app/templates/main_app/register.html
Labels: Level2, gssoc21, ready-to-merge

#188 Added new feature - NGO for Women webpage
  main_app/static/Images/ngo.jpg
  main_app/static/Images/ngologo.png
  main_app/templates/main_app/common.html
  main_app/templates/main_app/home.html
  main_app/templates/main_app/ngo_details.html
  main_app/urls.py
  main_app/views.py
Labels: Level2, gssoc21, ready-to-merge

#191 Created Register page using email id for user registration , issue #183
  main_app/forms.py
  main_app/models.py
  main_app/templates/main_app/common.html
  main_app/views.py
  mysite/urls.py
Labels: Level2, gssoc21, ready-to-merge

#202 Added back-to-top button
  main_app/static/css/styles.css
  main_app/static/js/index.js
  main_app/templates/main_app/404.html
  main_app/templates/main_app/common.html
  main_app/templates/main_app/create_contact.html
  main_app/templates/main_app/delete_contact.html
  main_app/templates/main_app/developers.html
  main_app/templates/main_app/emergency.html
  main_app/templates/main_app/emergency_contact.html
  main_app/templates/main_app/helpline_numbers.html
  main_app/templates/main_app/home.html
  main_app/templates/main_app/login.html
  main_app/templates/main_app/register.html
  main_app/templates/main_app/women_laws.html
  main_app/templates/main_app/women_rights.html
Labels: gssoc21, under review
