Repository swapnilsparsh/Rescue, pull requests merged in 2021-04, with the labels that each got.

#205 Whatsapp messaging added
  .gitignore
  main_app/forms.py
  main_app/mail.py
  main_app/migrations/0002_contact_mobile_no.py
  main_app/models.py
  main_app/templates/main_app/create_contact.html
  main_app/templates/main_app/emergency_contact.html
  main_app/views.py
  main_app/whatsapp.py
Labels: Level3, gssoc21, under review

#225 changes full navbar code
  main_app/templates/main_app/common.html
  main_app/templates/main_app/emergency.html
  main_app/templates/main_app/home.html
Labels: under review

#171 enhanced and modified footer issue #131
  db.sqlite3
  main_app/migrations/0002_login.py
  main_app/templates/main_app/common.html
  main_app/templates/main_app/home.html
  main_app/templates/main_app/password_reset.html
  main_app/templates/main_app/password_reset_done.html
  main_app/templates/main_app/password_reset_form.html
  main_app/templates/main_app/password_reset_sent.html
Labels: Level2, changes requested, gssoc21

#240 added check for username and email
  db.sqlite3
  main_app/templates/main_app/common.html
  main_app/templates/main_app/register.html
  main_app/urls.py
  main_app/views.py
  requirements.txt
Labels: Level3, gssoc21, ready-to-merge

#249 added a user manual at home page
  main_app/static/Images/contact.svg
  main_app/static/Images/empowerment.svg
  main_app/static/Images/help.svg
  main_app/static/Images/id.svg
  main_app/static/Images/red-bg.jpg
  main_app/templates/main_app/home.html
Labels: Level2, gssoc21, ready-to-merge

#276 welcome bot added
  .github/workflows/greetings.yml
Labels: gssoc21, ready-to-merge

#274 Added githtub action for auto-reply on pr merge
  .github/workflows/Auto_message_on_pr_merge.yml
Labels: gssoc21, ready-to-merge

#267 added Github link on footer
  db.sqlite3
  main_app/templates/main_app/common.html
  main_app/templates/main_app/home.html
Labels: gssoc21, ready-to-merge

#259 Adding Women Safety Numbers State wise
  main_app/templates/main_app/helpline_numbers.html
Labels: Level2, gssoc21, ready-to-merge

#252 added delete account feature
  main_app/templates/main_app/common.html
  main_app/templates/main_app/home.html
  main_app/urls.py
  main_app/views.py
  mysite/urls.py
Labels: Level3, gssoc21, ready-to-merge
